-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgdfwnoMoqboVTr3sl
RxgdRN7sZwUrP+2Z7Tr/hY9zL3KgCgYIKoZIzj0DAQehRANCAARD45jjuuCu93pO
o1um/aTy4gM+fMcHzsDGrCSxavUtxKvJiLl5+uUs1BDA/5UWbN6LLR7E5mt7lIvQ
sxwI/oVY
-----END PRIVATE KEY-----